<a href="https://colab.research.google.com/github/timmymalone/Data_Science/blob/main/Malone_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for i in range(10):# prints numbers up to 10 but not including
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(3):
    print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


In [ ]:
def square(x): #** is squaring
    return x**2

In [ ]:
square(12345)

152399025

In [ ]:
square(45)

2025

In [ ]:
square(square(square (2)))

256

In [ ]:
choice = "apple" #lbel command "apple"

In [ ]:
if choice =="apple":

   print("You choose apples.")

else:

     print("You did not choose apples.")

You choose apples.


In [ ]:
if choice =="apple": # commanding it to say you chooseapples

   print("You choose apples.")


elif choice == "orange":

  print("you choose oranges.")




else:

     print("You did not choose apples.")

You choose apples.


In [ ]:
if choice =="apple": #adding extra text

   print("You choose apples.")
   print ("Thank you, shop again!")

elif choice == "orange":

  print("you choose oranges.")
  print ("Thank you, shop again!")



else:

     print("You did not choose apples.")
     print ("Thank you, shop again!")

You choose apples.
Thank you, shop again!


In [ ]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): oranges


In [ ]:
choice

'oranges'

In [ ]:
import numpy as np


In [ ]:
np.random.permutation(52)#random numbers up to 52

array([ 0,  2, 13, 14,  1, 10, 37, 47, 42, 40,  3, 36, 29, 44, 25, 16,  5,
       26, 30, 46, 33, 38, 23, 15, 18, 39, 45, 20,  6, 21, 50, 27, 28, 35,
       19, 17, 48,  4, 22, 12, 11, 34,  9, 51, 24,  7,  8, 41, 43, 31, 32,
       49])

In [ ]:
cards = np.random.permutation(52)

In [ ]:
cards #can use that randomizer to randomize cards

array([ 0, 26, 14, 15,  7,  5, 40, 20, 28, 17, 30,  4, 50, 51, 25, 47, 23,
       38, 33, 45, 44, 43, 22, 24, 19, 12, 35,  3, 11,  1,  8, 16, 34,  6,
       39, 46, 32,  2, 27, 49, 31, 41, 29, 37,  9, 36, 13, 42, 10, 18, 21,
       48])

In [ ]:
cards[1]

26

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13)#reshaping cards

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13 #using %13 we can reset it to go 1-13 each new row

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13 #// groups all numbers in a row to be same number

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #naming cards
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [ ]:
def card_name(card_number):

    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [ ]:
card_name(0)

'Ace of Clubs'

In [ ]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

In [ ]:
i,j

(1, 6)

In [ ]:
suit[i]

'p'

In [ ]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [ ]:
card_image(3)

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img): #show card img
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card [j] + card_url_tail

In [ ]:
show_img(img)